remote_theme: pmarsceill/just-the-docs
title: CreatureBox Documentation
description: Comprehensive documentation for the CreatureBox wildlife monitoring system
search_enabled: true

# Color scheme
color_scheme: light

# Aux links for upper right navigation
aux_links:
  "CreatureBox on GitHub":
    - "//github.com/zane-lazare/creaturebox-refactor"

# Footer content 
footer_content: "CreatureBox Documentation - Generated on 2025-03-08"

# Collections for better organization
collections:
  core-components:
    permalink: "/:collection/:path/"
    output: true
  web-interface:
    permalink: "/:collection/:path/"
    output: true
  setup:
    permalink: "/:collection/:path/"
    output: true

# Just the Docs defaults
defaults:
  - scope:
      path: ""
      type: core-components
    values:
      layout: default
      parent: Core Components
  - scope:
      path: ""
      type: web-interface
    values:
      layout: default
      parent: Web Interface
  - scope:
      path: ""
      type: setup
    values:
      layout: default
      parent: Setup & Deployment

# Enable back to top button
back_to_top: true
back_to_top_text: "Back to top"

# Enable copy code button
enable_copy_code_button: true