remote_theme: pmarsceill/just-the-docs
title: CreatureBox Documentation
description: Comprehensive documentation for the CreatureBox wildlife monitoring system
search_enabled: true

# Color scheme
color_scheme: light

# Aux links for upper right navigation
aux_links:
  "CreatureBox on GitHub":
    - "//github.com/zane-lazare/creaturebox-refactor"

# Footer content 
footer_content: "CreatureBox Documentation - Generated on 2025-03-08"

# Navigation structure
nav_external_links:
  - title: GitHub Repository
    url: https://github.com/zane-lazare/creaturebox-refactor

# Default base layout
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Enable back to top button
back_to_top: true
back_to_top_text: "Back to top"

# Enable copy code button
enable_copy_code_button: true